# Generated by Django 5.0.2 on 2024-03-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyazIsler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bilgisi', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='KontrolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('chassis', models.CharField(max_length=17, unique=True, verbose_name='Şasi No')),
                ('model', models.CharField(choices=[('---', 'Boş'), ('AYAZ SMART', 'Ayaz Smart'), ('AYAZ COMFORT', 'Ayaz Comfort'), ('AYAZ PREMIUM', 'Ayaz Premium'), ('AYAZ OFFROAD SMART', 'Ayaz OffRoad Smart'), ('AYAZ OFFROAD COMFORT', 'Ayaz OffRoad Comfort'), ('AYAZ OFFROAD PREMIUM', 'Ayaz OffRoad Premium'), ('ARKUT SMART', 'Arkut Smart'), ('ARKUT COMFORT', 'Arkut Comfort'), ('ARKUT PREMIUM', 'Arkut Premium'), ('ALADA PREMIUM', 'Alada Premium'), ('GREDIA PREMIUM', 'Gredia Premium')], default='---', max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Kontrol',
                'verbose_name_plural': 'Kontroller',
            },
        ),
        migrations.CreateModel(
            name='KaravanIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi_mi', models.BooleanField(default=False)),
                ('is_bilgisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kontrol.ayazisler')),
                ('karavan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kontrol.kontrolclass')),
            ],
            options={
                'unique_together': {('karavan', 'is_bilgisi')},
            },
        ),
        migrations.AddField(
            model_name='ayazisler',
            name='karavanlar',
            field=models.ManyToManyField(through='Kontrol.KaravanIs', to='Kontrol.kontrolclass'),
        ),
    ]
