# Generated by Django 5.0.2 on 2024-03-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayazisler',
            options={'verbose_name': 'Ayaz İş', 'verbose_name_plural': 'Ayaz İşler'},
        ),
        migrations.AlterModelOptions(
            name='karavanis',
            options={'verbose_name': 'Karavan-İş', 'verbose_name_plural': 'Karavan-İş Tümü'},
        ),
        migrations.AlterField(
            model_name='ayazisler',
            name='is_bilgisi',
            field=models.CharField(max_length=400, verbose_name='İş Bilgisi'),
        ),
        migrations.AlterField(
            model_name='karavanis',
            name='tamamlandi_mi',
            field=models.CharField(default='KALDI', max_length=20, verbose_name='Durum'),
        ),
    ]
