# Generated by Django 5.0.2 on 2024-03-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kontrol', '0002_alter_ayazisler_options_alter_karavanis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karavanis',
            name='is_bilgisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kontrol.ayazisler', verbose_name='İş Bilgisi'),
        ),
        migrations.AlterField(
            model_name='karavanis',
            name='karavan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kontrol.kontrolclass', verbose_name='Karavan'),
        ),
        migrations.AlterField(
            model_name='karavanis',
            name='tamamlandi_mi',
            field=models.CharField(choices=[('KALDI', 'KALDI'), ('GEÇTİ', 'GEÇTİ')], default='KALDI', max_length=20, verbose_name='Durum'),
        ),
    ]
