# Generated by Django 5.0.2 on 2024-03-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kontrol', '0003_alter_karavanis_is_bilgisi_alter_karavanis_karavan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayazisler',
            name='bolum',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kısım'),
        ),
    ]
